In [140]:
import numpy as np
import pandas as pd
data = pd.read_csv('all_kindle_review.csv')
data

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [141]:
df=data[['reviewText','rating']]
df

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [142]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [143]:
df['rating']=df['rating'].apply(lambda x:1 if x>3 else 0 )
df['reviewText']=df['reviewText'].str.lower()

C:\Users\amiya\AppData\Local\Temp\ipykernel_41096\1305968631.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:1 if x>3 else 0 )
C:\Users\amiya\AppData\Local\Temp\ipykernel_41096\1305968631.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()


In [144]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [145]:
df

reviewText  rating
0      jace rankin may be short, but he's nothing to ...       0
1      great short read.  i didn't want to put it dow...       1
2      i'll start by saying this is the first of four...       0
3      aggie is angela lansbury who carries pocketboo...       0
4      i did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  valentine cupid is a vampire- jena and ian ano...       1
11996  i have read all seven books in this series. ap...       1
11997  this book really just wasn't my cuppa.  the si...       0
11998  tried to use it to charge my kindle, it didn't...       0
11999  taking instruction is a look into the often hi...       0

[12000 rows x 2 columns]

In [146]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

In [147]:
def cleaning(sentence):
   review=re.sub('[^a-zA-z]',' ',sentence)
   review=review.lower()
   review=review.split()
   return review
def processing(sentence):
   words=[]
   for i in range(0,len(sentence)):
      if sentence[i] not in stopwords.words('english'):
          sentence[i]=wl.lemmatize(sentence[i],pos='v')
          words.append(sentence[i])

   return words
df['reviewText']=df['reviewText'].apply(lambda x: processing(cleaning(x)))



C:\Users\amiya\AppData\Local\Temp\ipykernel_41096\99058377.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: processing(cleaning(x)))


In [148]:
df

reviewText  rating
0      [jace, rankin, may, short, nothing, mess, man,...       0
1      [great, short, read, want, put, read, one, sit...       1
2      [start, say, first, four, book, expect, conclu...       0
3      [aggie, angela, lansbury, carry, pocketbooks, ...       0
4      [expect, type, book, library, please, find, pr...       1
...                                                  ...     ...
11995  [valentine, cupid, vampire, jena, ian, another...       1
11996  [read, seven, book, series, apocalyptic, adven...       1
11997  [book, really, cuppa, situation, man, capture,...       0
11998  [try, use, charge, kindle, even, register, cha...       0
11999  [take, instruction, look, often, hide, world, ...       0

[12000 rows x 2 columns]

In [149]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],random_state=42,test_size=0.25,)
x_train

11675    [short, enough, read, chili, cook, keep, inter...
10950    [jolene, benate, top, world, covet, spot, warr...
4256     [man, load, one, let, see, year, old, virgin, ...
10088    [character, good, like, way, main, character, ...
9030     [much, say, hot, good, story, quick, read, wor...
                               ...                        
11964    [download, book, read, review, usually, read, ...
5191     [far, one, hottest, book, ever, get, hand, mis...
5390     [even, though, book, free, reservations, base,...
860      [little, mushy, must, take, care, women, folk,...
7270     [book, good, good, set, charaters, background,...
Name: reviewText, Length: 9000, dtype: object

In [150]:
from gensim.models import keyedvectors
model = "C:/Users/amiya/OneDrive/Documents/word2vecmodel/archive/GoogleNews-vectors-negative300.bin"
vectoriser = keyedvectors.load_word2vec_format(model, binary=True)

In [151]:
def avgw2v(doc):
  return np.mean([vectoriser[word] for word in doc if word in vectoriser.key_to_index],axis=0) 


In [152]:
from tqdm import tqdm
x_train_b = []
for i in tqdm(range(len(x_train))):
    x_train_b.append(avgw2v(x_train.iloc[i]))
x_train_b=np.array(x_train_b)
x_train_b


100%|██████████| 9000/9000 [00:02<00:00, 3892.74it/s]


array([[ 0.0119074 , -0.02747137,  0.00308782, ..., -0.03406375,
         0.01699898, -0.02575129],
       [ 0.04312298,  0.03884851,  0.00714688, ..., -0.06337163,
         0.01699831, -0.02532381],
       [ 0.04285224, -0.00556925, -0.01162736, ..., -0.05622506,
        -0.00227178, -0.00843149],
       ...,
       [ 0.04125778, -0.01008717,  0.00478584, ..., -0.05021916,
        -0.00114181,  0.00388115],
       [ 0.03456624,  0.05065881,  0.01787531, ..., -0.05932908,
         0.02715229, -0.01829384],
       [ 0.00989385,  0.05366173,  0.01182786, ..., -0.0326003 ,
         0.0262354 , -0.02151191]], dtype=float32)

In [153]:
y_train=np.array(y_train)
x_train_b.shape

(9000, 300)

In [154]:
train_data=pd.DataFrame(x_train_b)
train_data['output']=y_train
train_data

0         1         2         3         4         5         6  \
0     0.011907 -0.027471  0.003088  0.181524 -0.100605  0.012840  0.071198   
1     0.043123  0.038849  0.007147  0.083439 -0.062681  0.007376  0.074285   
2     0.042852 -0.005569 -0.011627  0.075537 -0.065929  0.003283  0.083210   
3     0.080270  0.020499  0.029044  0.069266 -0.031529  0.052608  0.118879   
4     0.061021 -0.027255 -0.016958  0.102755 -0.052824  0.031212  0.097993   
...        ...       ...       ...       ...       ...       ...       ...   
8995 -0.012953 -0.013146 -0.041432  0.121464 -0.031826  0.015621  0.020171   
8996  0.017981 -0.053870 -0.019873  0.047614 -0.019354  0.043091  0.039941   
8997  0.041258 -0.010087  0.004786  0.081372 -0.053805 -0.042924  0.058562   
8998  0.034566  0.050659  0.017875  0.118030 -0.075902  0.010987  0.071083   
8999  0.009894  0.053662  0.011828  0.079614 -0.054273 -0.029631  0.047195   

             7         8         9  ...       291       292       293  \
0    -0.031414  0.101350  0.018230  ...  0.077520 -0.103210  0.057366   
1    -0.083351  0.085251  0.064202  ...  0.076688 -0.098589  0.007533   
2    -0.028072  0.078169  0.073702  ...  0.068001 -0.090673 -0.019292   
3    -0.001999  0.044852  0.112070  ...  0.051884 -0.069750 -0.019932   
4    -0.014315  0.079984  0.065031  ... -0.007230 -0.027353  0.059908   
...        ...       ...       ...  ...       ...       ...       ...   
8995  0.028907  0.103183 -0.001560  ... -0.013658 -0.045078  0.036381   
8996 -0.085474  0.080750  0.120947  ...  0.011282 -0.076929  0.050366   
8997 -0.057656  0.111107  0.043452  ...  0.050585 -0.105936  0.012410   
8998 -0.023857  0.055176  0.029975  ...  0.062165 -0.104289 -0.018515   
8999 -0.056941  0.050131  0.047267  ...  0.064857 -0.063889 -0.011842   

           294       295       296       297       298       299  output  
0    -0.020058 -0.012706 -0.006076 -0.034064  0.016999 -0.025751       1  
1    -0.064509 -0.025258 -0.003273 -0.063372  0.016998 -0.025324       0  
2    -0.087806 -0.019175  0.034459 -0.056225 -0.002272 -0.008431       0  
3    -0.051928  0.011751  0.044034 -0.123526  0.026906 -0.006627       1  
4    -0.011348 -0.083285 -0.007679 -0.070200 -0.034829 -0.030536       1  
...        ...       ...       ...       ...       ...       ...     ...  
8995  0.002092 -0.095789 -0.026620 -0.098249 -0.019683 -0.029404       0  
8996 -0.004987 -0.076904 -0.023590 -0.064754  0.014551 -0.026119       1  
8997 -0.007600 -0.040105  0.003874 -0.050219 -0.001142  0.003881       0  
8998 -0.078902 -0.012944  0.043639 -0.059329  0.027152 -0.018294       0  
8999 -0.048808 -0.042973  0.025732 -0.032600  0.026235 -0.021512       1  

[9000 rows x 301 columns]

In [156]:
from sklearn.naive_bayes import GaussianNB
ML_model=GaussianNB()
x = train_data.iloc[:,:-1]
y=train_data.iloc[:,-1]
ML_model.fit(x, y)

GaussianNB()

In [ ]:
x_test_b = []
for i in tqdm(range(len(x_test))):
    x_test_b.append(avgw2v(x_test.iloc[i]))
x_test_b=np.array(x_test_b)
x_test_b

100%|██████████| 3000/3000 [00:00<00:00, 6661.43it/s]


array([[ 3.28826904e-02,  3.58123779e-02,  1.80816650e-02, ...,
        -6.28662109e-03,  5.98487854e-02, -5.30090332e-02],
       [ 6.30770624e-02,  2.16300264e-02,  1.42938793e-01, ...,
        -1.11318417e-01,  4.61092871e-03, -1.78389121e-02],
       [ 7.77384415e-02,  4.47184257e-02,  1.14059448e-03, ...,
        -2.68478394e-02, -5.13458252e-03, -1.00784302e-01],
       ...,
       [ 5.57809323e-02,  1.23945754e-02,  1.09845251e-02, ...,
        -5.08160144e-02,  7.40744872e-05, -4.00346220e-02],
       [ 2.58799959e-02,  1.36500761e-01, -5.47136590e-02, ...,
        -4.74243164e-02,  1.53443469e-02,  5.84967472e-02],
       [ 4.47981544e-02,  5.08868247e-02, -4.54571694e-02, ...,
        -1.16419196e-01,  8.68018903e-03,  1.55148897e-02]], dtype=float32)

In [ ]:
y_test=np.array(y_test)
x_test_b.shape

(3000, 300)

In [ ]:
test_data=pd.DataFrame(x_test_b)
test_data['output']=y_test
test_data

0         1         2         3         4         5         6  \
0     0.032883  0.035812  0.018082  0.159790 -0.022598 -0.000900  0.136688   
1     0.063077  0.021630  0.142939  0.148038 -0.065896 -0.037995  0.042866   
2     0.077738  0.044718  0.001141  0.093852 -0.037887  0.071737  0.099518   
3     0.076220  0.018060 -0.017511  0.083014 -0.045110  0.020393  0.096999   
4     0.063592  0.010520  0.022256  0.125792 -0.089499 -0.005451  0.071824   
...        ...       ...       ...       ...       ...       ...       ...   
2995  0.062976 -0.011174 -0.017570  0.089823 -0.042230  0.004402  0.065562   
2996  0.047705  0.034418 -0.050434  0.094873  0.030612  0.057037  0.057479   
2997  0.055781  0.012395  0.010985  0.134338 -0.051327 -0.003854  0.061500   
2998  0.025880  0.136501 -0.054714  0.063250 -0.039045 -0.037798  0.136143   
2999  0.044798  0.050887 -0.045457  0.081797 -0.024129 -0.004613  0.143807   

             7         8         9  ...       291       292       293  \
0     0.005936  0.045868  0.005524  ...  0.026077 -0.078613  0.033661   
1    -0.040993  0.132729  0.048495  ...  0.075484 -0.090243 -0.018727   
2     0.040802  0.081045  0.067713  ...  0.007418 -0.099375  0.031840   
3    -0.037416  0.083887  0.075797  ...  0.058155 -0.113636  0.020368   
4    -0.009530  0.103889  0.073318  ...  0.035728 -0.079899  0.026094   
...        ...       ...       ...  ...       ...       ...       ...   
2995 -0.041523  0.090062  0.050348  ...  0.055973 -0.116870  0.006156   
2996 -0.003347  0.103015  0.036820  ...  0.029315 -0.109363 -0.003726   
2997 -0.065439  0.069037  0.094980  ...  0.068363 -0.089589 -0.028908   
2998  0.018079  0.099139  0.095630  ...  0.071069 -0.119071 -0.080793   
2999  0.002135  0.086289  0.048520  ...  0.007144 -0.103614 -0.008728   

           294       295       296       297       298       299  output  
0    -0.043213 -0.049927  0.008190 -0.006287  0.059849 -0.053009       0  
1    -0.069862 -0.164418 -0.054610 -0.111318  0.004611 -0.017839       0  
2    -0.006371 -0.084493  0.024307 -0.026848 -0.005135 -0.100784       0  
3    -0.063033 -0.047969  0.039024 -0.033521  0.019856 -0.017743       0  
4    -0.079213 -0.050541 -0.009577 -0.040910 -0.020019 -0.003398       0  
...        ...       ...       ...       ...       ...       ...     ...  
2995 -0.033157 -0.038966  0.047058 -0.064540  0.000779  0.008970       0  
2996 -0.034460 -0.100279  0.017030 -0.038776 -0.044908  0.032553       1  
2997 -0.034932 -0.069569  0.002019 -0.050816  0.000074 -0.040035       1  
2998 -0.084298  0.049810  0.026816 -0.047424  0.015344  0.058497       0  
2999 -0.078857 -0.093291 -0.016578 -0.116419  0.008680  0.015515       1  

[3000 rows x 301 columns]

In [159]:
x_test=test_data.iloc[:,:-1]
y_test=test_data.iloc[:,-1]
y_predict=ML_model.predict(x_test)
y_predict

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [160]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
score=accuracy_score(y_test,y_predict)
score

0.718

In [161]:
classification_report(y_test,y_predict)

'              precision    recall  f1-score   support\n\n           0       0.69      0.80      0.74      1501\n           1       0.76      0.63      0.69      1499\n\n    accuracy                           0.72      3000\n   macro avg       0.72      0.72      0.72      3000\nweighted avg       0.72      0.72      0.72      3000\n'

In [162]:
confusion_matrix(y_test,y_predict)

array([[1204,  297],
       [ 549,  950]], dtype=int64)

In [163]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(n_jobs=-1,random_state=42)
lr.fit(x,y)

LogisticRegression(n_jobs=-1, random_state=42)

In [164]:
y_predict_2=lr.predict(x_test)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
score=accuracy_score(y_test,y_predict_2)
score

0.7953333333333333

In [165]:
classification_report(y_test,y_predict_2)

'              precision    recall  f1-score   support\n\n           0       0.79      0.80      0.80      1501\n           1       0.80      0.79      0.79      1499\n\n    accuracy                           0.80      3000\n   macro avg       0.80      0.80      0.80      3000\nweighted avg       0.80      0.80      0.80      3000\n'

In [166]:
confusion_matrix(y_test,y_predict_2)

array([[1200,  301],
       [ 313, 1186]], dtype=int64)

In [168]:
import pickle
pickle.dump(lr,open("model.pkl",'wb'))

In [169]:
vectoriser.save("vectoriser.model")